
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - service
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extersions/v1beta1
  resources:
  - ingress
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - traefik.porpaul
  resources:
  - traefikredirects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - traefik.porpaul
  resources:
  - traefikredirects/finalizers
  verbs:
  - update
- apiGroups:
  - traefik.porpaul
  resources:
  - traefikredirects/status
  verbs:
  - get
  - patch
  - update
