# permissions for end users to edit traefikredirects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefikredirect-editor-role
rules:
- apiGroups:
  - traefik.porpaul
  resources:
  - traefikredirects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - traefik.porpaul
  resources:
  - traefikredirects/status
  verbs:
  - get
